// <auto-generated />
namespace BrightBoxTest.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StatusMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatusMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201512041139039_StatusMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
